[env]
PATH = "./build:{{env.PATH}}"

[tools]
cmake = "3"
lua = "5.1"

[tasks.setup]
description = "Setup the project"
run = "test -d build || cmake -S . -B build"
alias = "s"

[tasks.build]
description = "Build the project"
run = "cmake --build build"
depends = ["setup"]
alias = "b"

[tasks.clean]
description = "Clean the project"
run = "cmake --build build --target clean"
alias = "c"
