/*
 * EDITING THIS FILE DIRECTLY WON'T DO ANYTHING
 *
 * This file is autogenerated by CMake depending on the provided plugins
 * See the main CMakeLists.txt file and, specifically, the PLUGIN_INCLUDES
 * variable and it's uses for more information
 */
