name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

      - name: Cache Tools
        uses: actions/cache@v4
        with:
          path: ~/.local/share/mise
          key: mise-${{ runner.os }}-${{ hashFiles('mise.toml') }}

      - name: Install Tools
        run: |
          mise install --yes

      - name: Cache Dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            subprojects/**
            !subprojects/*.wrap
          key: deps-${{ runner.os }}-${{ hashFiles('subprojects/*.wrap') }}

      - name: Setup Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mise run setup

      - name: Build
        run: mise run build

